spring.application.name=BBOTS


spring.datasource.url=jdbc:postgresql://15.206.148.49:5432/postgres?currentSchema=connect_dev,finance_dev,fixed_assets,public
spring.datasource.username=bav
spring.datasource.password=Bav@1234
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=600000

mybatis.mapper-locations=classpath:mappers/*.xml
mybatis.type-aliases-package=com.example.demo.modules.users.mapper,com.example.demo.modules.role.mapper
mybatis.configuration.map-underscore-to-camel-case=true


